import "./globals.css";
import {Ranga} from 'next/font/google'

export const metadata = {
  title: "Next.js Demo App",
  description: "Generated by create next app",
};

const ranga = Ranga({
  subsets:['latin'], 
  weight:'700',
  variable: '--font-ranga-bold'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center min-h-screen font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
