import { GRID_DATA_ITEMS} from '../data'
import Link from 'next/link';

export const metadata = {
  title: "Next.js Demo App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
        <div className="w-full max-w-[1000px] flex flex-col items-center pt-6 pb-6 px-4">
          
          <div className="w-full bg-slate-200/75 shadow-md rounded-lg p-6">
            <h2 className="text-2xl font-bold text-center mb-6 underline decoration-4 decoration-blue-400">MUSIC</h2>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 justify-items-center">
              {GRID_DATA_ITEMS.map(({ id, attributes }) => (
                <Link key={id} href={attributes.href} className="group">
                  <div className={`${attributes.background} w-40 h-40 flex items-end justify-center border-2 border-black rounded-lg transition-transform group-hover:scale-105`}>
                    <span className="text-white font-semibold mb-2 text-center">{attributes.text}</span>
                  </div>
                </Link>
              ))}
            </div>
          </div>

          <main className="w-full mt-10">{children}</main>
        </div>
  );
}
